# Generated by Django 3.2.7 on 2021-09-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('disciption', models.CharField(blank=True, max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('eligibility', models.CharField(blank=True, max_length=500)),
                ('link', models.URLField(max_length=500)),
                ('discription', models.CharField(blank=True, max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/lessonimage/')),
                ('category', models.ManyToManyField(to='official_use.Category')),
            ],
        ),
    ]
