# Generated by Django 3.2.7 on 2021-09-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_use', '0003_auto_20210912_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='discription',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
