# Generated by Django 3.2.7 on 2021-09-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_use', '0004_alter_lesson_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='disciption',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
