# Generated by Django 3.2.7 on 2021-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_use', '0005_alter_category_disciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categoryimage/'),
        ),
    ]
