# Generated by Django 3.2.7 on 2021-09-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official_use', '0006_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='disciption',
            new_name='discription',
        ),
    ]
