# Generated by Django 3.2.7 on 2021-09-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_use', '0007_rename_disciption_category_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
