# Generated by Django 3.2.7 on 2021-09-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='disciption',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='discription',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='eligibility',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
