# Generated by Django 3.2.7 on 2021-09-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0002_auto_20210911_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
